import { ArrowDown, ArrowUpRight, Download, MousePointer2 } from "lucide-react";
import { productLinks } from "@/lib/product";
import { SiteShowcase } from "./_components/SiteShowcase";
import { Venue } from "./_components/Brand";
import { NansenAttribution } from "./_components/NansenAttribution";

export const dynamic="force-dynamic";

export default function ProductPage(){
  const links=productLinks();
  return <div className="product research-site">
    <section className="product-hero" aria-labelledby="hero-title">
      <div className="hero-copy"><NansenAttribution/>
        <h1 id="hero-title">Onchain intelligence.<br/><span>In your browser.</span></h1>
        <p className="hero-description">The wallet behind the post. The flows behind the token.<br/>Tripwire brings Nansen to the places you already trade.</p>
        <div className="hero-actions"><a href="#install" className="product-button"><Download size={18} aria-hidden="true"/>Get Tripwire for Chrome</a><a className="hero-see" href="#in-action">See it in action<ArrowDown size={16} aria-hidden="true"/></a>{links&&<a className="hero-see" href={links.repository} target="_blank" rel="noopener noreferrer">View on GitHub<ArrowUpRight size={16} aria-hidden="true"/></a>}</div>
      </div>
    </section>
    <SiteShowcase/>
    <section className="venue-band" aria-label="Supported sites"><p>Works where<br/><strong>you already are.</strong></p><div className="venue-list"><span className="product-x">𝕏 <span>X</span></span>{["dexscreener","uniswap","jumper","hyperliquid","polymarket"].map(id=><Venue key={id} id={id}/>)}</div></section>
    <section id="features" className="workflow-section" aria-labelledby="features-title"><div><span className="brief-kicker">WITHOUT SWITCHING TABS</span><h2 id="features-title">A little more context.<br/>Right where you need it.</h2><p>Open a Nansen badge to inspect the wallet, token or market already on your screen.</p></div><div className="workflow-rows"><article><span>01</span><div><h3>A name becomes a profile.</h3><p>Open available Nansen wallet or entity insights beside a post or trader’s name.</p></div></article><article><span>02</span><div><h3>A token gets its context.</h3><p>See flows and holders for the exact selected contract. Other chains and perp markets stay clearly separate.</p></div></article><article><span>03</span><div><h3>A position gets a second look.</h3><p>On Hyperliquid, inspect perp positioning, funding and reported liquidation levels.</p></div></article></div></section>
    <section id="install" className="install-section" aria-labelledby="install-title"><div className="install-intro"><span className="brief-kicker">TAKE IT WITH YOU</span><h2 id="install-title">Install Tripwire.</h2><p>Download the packaged extension from GitHub and add it to desktop Chrome. No account, no key, no server to run.</p><NansenAttribution compact/>{links?<a className="product-button" href={links.download}><Download size={16} aria-hidden="true"/>Download extension (.zip)</a>:<><button className="product-button" disabled aria-describedby="release-note"><Download size={16} aria-hidden="true"/>Download coming soon</button><p id="release-note" className="release-note">The public package isn’t available yet. Its release link will appear here.</p></>}{links&&<><a className="repository-link" href={links.release} target="_blank" rel="noopener noreferrer">All releases<ArrowUpRight size={14} aria-hidden="true"/></a><a className="repository-link" href={links.repository} target="_blank" rel="noopener noreferrer">Source on GitHub<ArrowUpRight size={14} aria-hidden="true"/></a></>}</div><ol className="install-guide"><li><span>1</span><div><h3>Download the ZIP</h3><p>Unzip <code>tripwire-extension.zip</code> into a folder you’ll keep.</p></div></li><li><span>2</span><div><h3>Add it in Chrome</h3><p>Open <code>chrome://extensions</code>, enable Developer mode and choose <strong>Load unpacked</strong>. Select the folder containing <code>manifest.json</code>.</p></div></li><li><span>3</span><div><h3>Pin it and browse</h3><p>Pin Tripwire and open X or a supported venue. It connects on its own; nothing to set up.</p></div></li></ol></section>
    <section id="faq" className="product-faq" aria-labelledby="faq-title"><h2 id="faq-title">A few details.</h2><div className="faq-list"><details><summary>Are these screenshots from the extension?</summary><p>Yes. They show Tripwire running on the named sites. The figures were recorded when each screenshot was taken; they are not live quotes.</p></details><details><summary>Does every wallet or token have data?</summary><p>Coverage depends on the asset, chain and available Nansen data. Tripwire keeps each token’s contract and chain explicit, and shows when information is unavailable.</p></details><details><summary>Does Tripwire trade for me?</summary><p>No. Tripwire presents evidence and can flag trades when your rules fire. You choose what to do and sign in your trading app. This information is not a guarantee of safety.</p></details><details><summary>What do I need to use the extension?</summary><p>Desktop Chrome and a configured Tripwire data connection. The current development build uses a local service. The public release will describe its setup requirements.</p></details></div></section>
    <div className="product-closing"><MousePointer2 size={16} aria-hidden="true"/><span>Tripwire puts Nansen beside your next decision.</span><a href="#install">Get the extension<ArrowUpRight size={14} aria-hidden="true"/></a></div>
  </div>;
}
